
CREATE TABLE student(
    RegNo INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(25) NOT NULL,
    MiddleName VARCHAR(25),
    LastName VARCHAR(25) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    PermanentAddress VARCHAR(100) NOT NULL,
    TemporaryAddress VARCHAR(100) NOT NULL,
    Mobile VARCHAR(10) UNIQUE NOT NULL,
    Email VARCHAR(25) UNIQUE NOT NULL,
    DOB DATE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);